name: Deployning to Production

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-repo
        uses: actions/checkout@v2

      - name: Docker-login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}    
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Docker-build-web-push-image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.prod.web
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/web:${{ github.sha }}    

      - name: Docker-build-(backend-auth)-image-push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.prod.backend-auth
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/backend-auth:${{ github.sha }}  
   
   
      - name: Clone repo of ops and change img both fe and be
        env:
          OPS_REPO_PAT: ${{ secrets.OPS_REPO_PAT }} 
        run: | 
            git clone https://github.com/spi9325/ops.git
            cd ops 
            sed -i "s|image: spi9325/backend-auth:.*|image: spi9325/backend-auth:${{ github.sha }}|" Deployment-be.yml
            sed -i "s|image: spi9325/web:.*|image: spi9325/web:${{ github.sha }}|" Deployment-web.yml

            git config user.name "Github Actions Bot"
            git config user.email "actions@github.com"
            git add .
            git commit -m "adding latest commit"
            git push https://${OPS_REPO_PAT}@github.com/spi9325/ops.git main
            